### ISSUE TITLE
Final iOS Updates

### ISSUE THREAD

**Issue by russell-davis** [ParadigmCreative/HumanityHospice-iOS#6]
*These changes are for iOS and Android*

Photo Album
- [x] As a patient, we need to be able to delete photos from the album

Journal
- [x] Posts and comments need to be editable and deleteable

Encouragement Board
- [x] Posts need be editable and deleteable

Menu
- [x] Switch Patients not showing -> Double check this

**Comment by russell-davis** [comment]
Also check that correct profile pictures are being set on posts and comments

**Comment by russell-davis** [comment]
- [ ] 1. When deleting a picture from the photo album that was originally posted from a journal entry, the app crashes
    - [ ] When user clicks delete, search through local storage (journal posts) to see if that image exists as a journal post; if it does, set hasImage to false, and imageURL to nil.
- [ ] 2. Images are jumbled when on journal and encouragement board
- [ ] 3. Profile picture is not showing (blank) on encouragement board
- [ ] 4. when making a journal / photo album post with image, (composing) the profile picture needs to update with the current user
- [ ] 5. Photo album loading oddly

**Comment by msrusse** [comment]
@russell-davis are these issues on both or only iOS?

**Comment by russell-davis** [comment]
Fixed - 3a4f22f100a9dcb84563a75594bfd23764e258bf
